# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="calc.proto",
    package="calc",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\ncalc.proto\x12\x04\x63\x61lc"$\n\nAddRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05"\x16\n\x08\x41\x64\x64Reply\x12\n\n\x02n1\x18\x01 \x01(\x05"*\n\x10SubstractRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05"\x1c\n\x0eSubstractReply\x12\n\n\x02n1\x18\x01 \x01(\x05")\n\x0fMultiplyRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05"\x1b\n\rMultiplyReply\x12\n\n\x02n1\x18\x01 \x01(\x05"\'\n\rDivideRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05"\x19\n\x0b\x44ivideReply\x12\n\n\x02\x66\x31\x18\x01 \x01(\x02\x32\xe2\x01\n\nCalculator\x12)\n\x03\x41\x64\x64\x12\x10.calc.AddRequest\x1a\x0e.calc.AddReply"\x00\x12;\n\tSubstract\x12\x16.calc.SubstractRequest\x1a\x14.calc.SubstractReply"\x00\x12\x38\n\x08Multiply\x12\x15.calc.MultiplyRequest\x1a\x13.calc.MultiplyReply"\x00\x12\x32\n\x06\x44ivide\x12\x13.calc.DivideRequest\x1a\x11.calc.DivideReply"\x00\x62\x06proto3'
    ),
)


_ADDREQUEST = _descriptor.Descriptor(
    name="AddRequest",
    full_name="calc.AddRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="n1",
            full_name="calc.AddRequest.n1",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="n2",
            full_name="calc.AddRequest.n2",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=20,
    serialized_end=56,
)


_ADDREPLY = _descriptor.Descriptor(
    name="AddReply",
    full_name="calc.AddReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="n1",
            full_name="calc.AddReply.n1",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=58,
    serialized_end=80,
)


_SUBSTRACTREQUEST = _descriptor.Descriptor(
    name="SubstractRequest",
    full_name="calc.SubstractRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="n1",
            full_name="calc.SubstractRequest.n1",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="n2",
            full_name="calc.SubstractRequest.n2",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=82,
    serialized_end=124,
)


_SUBSTRACTREPLY = _descriptor.Descriptor(
    name="SubstractReply",
    full_name="calc.SubstractReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="n1",
            full_name="calc.SubstractReply.n1",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=126,
    serialized_end=154,
)


_MULTIPLYREQUEST = _descriptor.Descriptor(
    name="MultiplyRequest",
    full_name="calc.MultiplyRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="n1",
            full_name="calc.MultiplyRequest.n1",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="n2",
            full_name="calc.MultiplyRequest.n2",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=156,
    serialized_end=197,
)


_MULTIPLYREPLY = _descriptor.Descriptor(
    name="MultiplyReply",
    full_name="calc.MultiplyReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="n1",
            full_name="calc.MultiplyReply.n1",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=199,
    serialized_end=226,
)


_DIVIDEREQUEST = _descriptor.Descriptor(
    name="DivideRequest",
    full_name="calc.DivideRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="n1",
            full_name="calc.DivideRequest.n1",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="n2",
            full_name="calc.DivideRequest.n2",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=228,
    serialized_end=267,
)


_DIVIDEREPLY = _descriptor.Descriptor(
    name="DivideReply",
    full_name="calc.DivideReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="f1",
            full_name="calc.DivideReply.f1",
            index=0,
            number=1,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=269,
    serialized_end=294,
)

DESCRIPTOR.message_types_by_name["AddRequest"] = _ADDREQUEST
DESCRIPTOR.message_types_by_name["AddReply"] = _ADDREPLY
DESCRIPTOR.message_types_by_name["SubstractRequest"] = _SUBSTRACTREQUEST
DESCRIPTOR.message_types_by_name["SubstractReply"] = _SUBSTRACTREPLY
DESCRIPTOR.message_types_by_name["MultiplyRequest"] = _MULTIPLYREQUEST
DESCRIPTOR.message_types_by_name["MultiplyReply"] = _MULTIPLYREPLY
DESCRIPTOR.message_types_by_name["DivideRequest"] = _DIVIDEREQUEST
DESCRIPTOR.message_types_by_name["DivideReply"] = _DIVIDEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequest = _reflection.GeneratedProtocolMessageType(
    "AddRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_ADDREQUEST,
        __module__="calc_pb2"
        # @@protoc_insertion_point(class_scope:calc.AddRequest)
    ),
)
_sym_db.RegisterMessage(AddRequest)

AddReply = _reflection.GeneratedProtocolMessageType(
    "AddReply",
    (_message.Message,),
    dict(
        DESCRIPTOR=_ADDREPLY,
        __module__="calc_pb2"
        # @@protoc_insertion_point(class_scope:calc.AddReply)
    ),
)
_sym_db.RegisterMessage(AddReply)

SubstractRequest = _reflection.GeneratedProtocolMessageType(
    "SubstractRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_SUBSTRACTREQUEST,
        __module__="calc_pb2"
        # @@protoc_insertion_point(class_scope:calc.SubstractRequest)
    ),
)
_sym_db.RegisterMessage(SubstractRequest)

SubstractReply = _reflection.GeneratedProtocolMessageType(
    "SubstractReply",
    (_message.Message,),
    dict(
        DESCRIPTOR=_SUBSTRACTREPLY,
        __module__="calc_pb2"
        # @@protoc_insertion_point(class_scope:calc.SubstractReply)
    ),
)
_sym_db.RegisterMessage(SubstractReply)

MultiplyRequest = _reflection.GeneratedProtocolMessageType(
    "MultiplyRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_MULTIPLYREQUEST,
        __module__="calc_pb2"
        # @@protoc_insertion_point(class_scope:calc.MultiplyRequest)
    ),
)
_sym_db.RegisterMessage(MultiplyRequest)

MultiplyReply = _reflection.GeneratedProtocolMessageType(
    "MultiplyReply",
    (_message.Message,),
    dict(
        DESCRIPTOR=_MULTIPLYREPLY,
        __module__="calc_pb2"
        # @@protoc_insertion_point(class_scope:calc.MultiplyReply)
    ),
)
_sym_db.RegisterMessage(MultiplyReply)

DivideRequest = _reflection.GeneratedProtocolMessageType(
    "DivideRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_DIVIDEREQUEST,
        __module__="calc_pb2"
        # @@protoc_insertion_point(class_scope:calc.DivideRequest)
    ),
)
_sym_db.RegisterMessage(DivideRequest)

DivideReply = _reflection.GeneratedProtocolMessageType(
    "DivideReply",
    (_message.Message,),
    dict(
        DESCRIPTOR=_DIVIDEREPLY,
        __module__="calc_pb2"
        # @@protoc_insertion_point(class_scope:calc.DivideReply)
    ),
)
_sym_db.RegisterMessage(DivideReply)


_CALCULATOR = _descriptor.ServiceDescriptor(
    name="Calculator",
    full_name="calc.Calculator",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=297,
    serialized_end=523,
    methods=[
        _descriptor.MethodDescriptor(
            name="Add",
            full_name="calc.Calculator.Add",
            index=0,
            containing_service=None,
            input_type=_ADDREQUEST,
            output_type=_ADDREPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="Substract",
            full_name="calc.Calculator.Substract",
            index=1,
            containing_service=None,
            input_type=_SUBSTRACTREQUEST,
            output_type=_SUBSTRACTREPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="Multiply",
            full_name="calc.Calculator.Multiply",
            index=2,
            containing_service=None,
            input_type=_MULTIPLYREQUEST,
            output_type=_MULTIPLYREPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="Divide",
            full_name="calc.Calculator.Divide",
            index=3,
            containing_service=None,
            input_type=_DIVIDEREQUEST,
            output_type=_DIVIDEREPLY,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name["Calculator"] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
