# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from src.proto.calc import calc_pb2 as calc__pb2


class CalculatorStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
            "/calc.Calculator/Add",
            request_serializer=calc__pb2.AddRequest.SerializeToString,
            response_deserializer=calc__pb2.AddReply.FromString,
        )
        self.Substract = channel.unary_unary(
            "/calc.Calculator/Substract",
            request_serializer=calc__pb2.SubstractRequest.SerializeToString,
            response_deserializer=calc__pb2.SubstractReply.FromString,
        )
        self.Multiply = channel.unary_unary(
            "/calc.Calculator/Multiply",
            request_serializer=calc__pb2.MultiplyRequest.SerializeToString,
            response_deserializer=calc__pb2.MultiplyReply.FromString,
        )
        self.Divide = channel.unary_unary(
            "/calc.Calculator/Divide",
            request_serializer=calc__pb2.DivideRequest.SerializeToString,
            response_deserializer=calc__pb2.DivideReply.FromString,
        )


class CalculatorServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Add(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Substract(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Multiply(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Divide(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Add": grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=calc__pb2.AddRequest.FromString,
            response_serializer=calc__pb2.AddReply.SerializeToString,
        ),
        "Substract": grpc.unary_unary_rpc_method_handler(
            servicer.Substract,
            request_deserializer=calc__pb2.SubstractRequest.FromString,
            response_serializer=calc__pb2.SubstractReply.SerializeToString,
        ),
        "Multiply": grpc.unary_unary_rpc_method_handler(
            servicer.Multiply,
            request_deserializer=calc__pb2.MultiplyRequest.FromString,
            response_serializer=calc__pb2.MultiplyReply.SerializeToString,
        ),
        "Divide": grpc.unary_unary_rpc_method_handler(
            servicer.Divide,
            request_deserializer=calc__pb2.DivideRequest.FromString,
            response_serializer=calc__pb2.DivideReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("calc.Calculator", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
